### ISSUE TITLE
Occasional Internal Error Returned

### ISSUE THREAD

**Issue by brrksl** [directus-labs/extension-ai-alt-text-writer#1]
In flows, occasionally an internal error is returned, especially when nothing has been run through the operation in a while (this seems to be key).

![Flow error](https://github.com/directus-labs/extension-ai-alt-text-writer/assets/5099805/4a86629c-6d23-415a-a166-44a94a813d02)

On a postman request to "https://api.clarifai.com/v2/users/salesforce/apps/blip/models/general-english-image-caption-blip/versions/cdb690f13e62470ea6723642044f95e4/outputs" with the same body as the extension uses - 
`{
  "inputs": [
    {
      "data": {
        "image": {
          "url": "{{directus install url}}/assets/b6aa5e80-bdaf-4f24-b93f-cd386f0a4c41"
        }
      }
    }
  ]
}`

It returns successfully -
`{
  "status": {
    "code": 10000,
    "description": "Ok",
    "req_id": "{{redacted}}"
  },
  "outputs": [
    {
      "id": "{{redacted}}",
      "status": {
        "code": 10000,
        "description": "Ok"
      },
      "created_at": "2024-05-23T00:00:35.406444311Z",
      "model": {
        "id": "general-english-image-caption-blip",
        "name": "Image Captioner",
        "created_at": "2022-04-18T20:01:32.067938Z",
        "modified_at": "2022-08-11T14:01:48.093093Z",
        "app_id": "blip",
        "model_version": {
          "id": "cdb690f13e62470ea6723642044f95e4",
          "created_at": "2023-04-11T21:40:32.444463Z",
          "status": {
            "code": 21100,
            "description": "Model is trained and ready"
          },
          "visibility": {
            "gettable": 50
          },
          "app_id": "blip",
          "user_id": "salesforce",
          "metadata": {}
        },
        "user_id": "salesforce",
        "model_type_id": "image-to-text",
        "visibility": {
          "gettable": 50
        },
        "toolkits": [],
        "use_cases": [],
        "languages": [],
        "languages_full": [],
        "check_consents": [],
        "workflow_recommended": false
      },
      "input": {
        "id": "{{redacted}}",
        "data": {
          "image": {
            "url": "{{redacted}}/assets/b6aa5e80-bdaf-4f24-b93f-cd386f0a4c41"
          }
        }
      },
      "data": {
        "text": {
          "raw": "a photograph of a man and woman taking a selfie with a rainbow - colored rainbow - colored",
          "text_info": {
            "encoding": "UnknownTextEnc"
          }
        }
      }
    }
  ]
}`

This seems like a clarifai/blip issue, but it is of course annoying to have some images return with alt text and others not. I don't personally know a fix, unfortunately, as I am not familiar enough with how clarifai functions or this blip. Maybe the model isn't ready? I see there is a V2 version of blip that may be used, but I assume it wasn't used for a reason.

**Comment by binaryben** [comment]
Hi @brrksl! Thanks for reporting this issue. I have copied it to https://github.com/directus-labs/extensions/issues/7 as we are migrating our lab extensions to a monorepo. Please follow that issue for any updates as this repository will be deleted in the next few days.
